POST http://localhost:5013/data/upsert
Content-Type: application/json

{
    "aboutDescription": "I love gaming!",
    "skills": "FPS, RPG, Strategy",
    "games": [

            "Counter-Strike 2",

            "Valorant"
    ],
    "availabilities": [
        {
            "dayOfWeek": 0,
            "startTime": "18:00:00+03:00",
            "endTime": "22:00:00+03:00"
        }
    ]
}