POST https://localhost/data/show/5
Cookie: GameTeam.Session=CfDJ8FTWX0RVbg1CnZD3HSxiGHvUd9ZSVRRW1lomL1XVWt%2FKzptsHkqGtVeQjyMHm9FYQU4ixrd9mGv9UF18BZBAApvfEJZ1HtGs0%2FiIjG8II9bUDjOG3IGYP%2FtizOToFgYak7HxJJ%2BoDKjCM5mCX6JVK7cK%2FZo%2BA%2BAxIB713hotmL0W